Lesson 12
selivanov-d/questions_answered pull request #10
Opened 2016-11-28 17:28 UTC by selivanov-d

Added Lesson 12

2016-11-28 18:38 UTC, vkurennov requested changes
Есть одна проблемка в коде, а в остальном - ок.

2016-11-28 18:38 UTC, vkurennov commented on app/assets/javascripts/templates/answer.jst.skim
> +  - if @best == true
Зачем сравнивать с true? В @best и так true или false, и `if @best` будет работать ровно так, как и должно. Т.е. сравнение с true/false в любом языке лишнее.

2016-11-28 18:38 UTC, vkurennov commented on app/controllers/omniauth_callbacks_controller.rb
> +    if @user && @user.persisted?
А если условия не выполнятся, что тогде будет? Надо покрыть этот кейс тестами

2016-11-29 08:36 UTC, selivanov-d commented on app/assets/javascripts/templates/answer.jst.skim
> +  - if @best == true
Да, действительно. 
Fixed.

2016-11-29 11:55 UTC, selivanov-d commented on app/controllers/omniauth_callbacks_controller.rb
> +    if @user && @user.persisted?
Добавил обработку варианта неполучения пользователя.
Тестируется это в acceptance-тестах.

2016-11-29 19:27 UTC, vkurennov commented on app/controllers/omniauth_callbacks_controller.rb
> +    if @user && @user.persisted?
По-хорошему, надо еще в тестах контроллера, ну ладно, главное, что есть тесты

2016-11-29 19:27 UTC, vkurennov approved these changes

2016-11-30 07:23 UTC, merged