Added lesson 18
selivanov-d/questions_answered pull request #16
Opened 2017-01-23 20:19 UTC by selivanov-d

2017-01-24 09:13 UTC, vkurennov requested changes

2017-01-24 09:13 UTC, vkurennov commented on app/controllers/searches_controller.rb
> +  def load_search
Т.к. фильтр используется только в одном экшене, то можно было и не псиать метод, а сразу в create и вызвать эту строку, так код стал бы понятнее. В фильтры имеет смысл выносить, если код используется в нескольких местах.

2017-01-24 09:13 UTC, vkurennov commented on app/controllers/searches_controller.rb
> +  def create_search
То же самое - не зачем было в фильтр выносить.

2017-01-24 09:13 UTC, vkurennov commented on app/models/search.rb
> +    @results if self.invalid?
Эта строка не вернет результат, метод дальше будет выполняться после нее, и в таком случае она вообще не имеет смысла. Чтобы завершить выполнение метода и сразу вернуть результат, нужно добавить return сюда

2017-01-24 09:13 UTC, vkurennov commented on app/models/search_result.rb
> +      when 'Question'
Вложенные case не очень хорошая идея, можно вынести вложенный case в приватный метод как минимум.

2017-01-24 09:13 UTC, vkurennov commented on app/models/search_result.rb
> +  def question
Не уверен, что это хорошая идея - ради одного метода, который просто берет нужную ассоциацию у объекта писать отдельный класс. Это тянет на хелпер (или декоратор), но не на модель.

2017-01-24 09:13 UTC, vkurennov commented on app/models/search_result.rb
> +  include ActiveModel::Model
И зачем тут этот модуль, что он дает?

2017-01-24 09:13 UTC, vkurennov commented on spec/models/search_spec.rb
> +    it 'performs search limited to questions when subject set to \'questions\'' do
Нужно для всех возможных вариантов написать тест. И еще нужен тест, когда объект невалидный.

2017-01-24 18:59 UTC, selivanov-d commented on spec/models/search_spec.rb
> +    it 'performs search limited to questions when subject set to \'questions\'' do
Добавил нужные тесты.

2017-01-24 19:01 UTC, selivanov-d commented on app/models/search_result.rb
> +  include ActiveModel::Model
Остатки каких-то экспериментов. Убрал.

2017-01-24 19:02 UTC, selivanov-d commented on app/models/search.rb
> +    @results if self.invalid?
Поправил.

2017-01-24 19:22 UTC, selivanov-d commented on app/models/search_result.rb
> +      when 'Question'
Разбил сложный case на пару приватных методов.

2017-01-24 19:27 UTC, selivanov-d commented on app/models/search_result.rb
> +  def question
Да, изначально я хотел сделать это декоратором с использованием гема Draper, но потом у меня с ним как-то не заладилось: модель Search почему-то не декорировалась через `search.decorate()` (или как-то так), потом с тестами возникли какие-то сложности (надо ли тестировать?.. если да, то как?..). В итоге решил отказаться от затеи и не тратить на это время и остановился на простом классе.
Оставлю, пожалуй, как есть сейчас.

2017-01-25 08:43 UTC, vkurennov commented on app/models/search_result.rb
> +  def question
В этом случае лучше всего было использовать обычные хелперы. Да, не объектно, но и класс городить не нужно и достаточно только acceptance-тестов.

2017-01-25 08:50 UTC, vkurennov requested changes
Раз уж оставил класс SearchResult, то напиши тесты на него. Ну и в текущей реализации, это скорее костыль, чем решение, без обид. Просто такой класс имел бы смысл, если бы он каким-то образом инкапсулировал результаты поиска и приводил бы его в единую форму в виде объекта, тогда ок, вопросов бы не было. А у тебя получается, что класс не представляет результаты, а просто ассоциацию декорирует. Можно, кстати, сделать его декоратором без всяких гемов, просто переименовать, скажем, в SearchResultDecorator и перенести в app/decorators (можно и не переименовывать, а просто перенести, чтобы обозначить, что это декоратор). Ну и в контроллере/модели уже использовать. 
Только тесты все равно надо написать.

2017-01-25 08:50 UTC, vkurennov commented on app/models/search_result.rb
> +class SearchResult
Кстати, коль уж это класс, то где тесты на него?

2017-01-26 08:42 UTC, vkurennov approved these changes

2017-01-26 13:35 UTC, merged