Lesson 5
selivanov-d/questions_answered pull request #3
Opened 2016-10-18 10:22 UTC by selivanov-d

Added Lesson 5

2016-10-18 13:46 UTC, vkurennov requested changes
Исправь замечания

2016-10-18 13:46 UTC, vkurennov commented on app/controllers/answers_controller.rb
>        render :new
Форма ответа должна быть на странице вопроса, а не на отдельной, поэтому и рендерить надо questions/show

2016-10-18 13:46 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if @answer.user == current_user
Здесь у тебя лишний запрос: ты тянешь юзера у ответа из базы, а ведь, чтобы проверить автора, достаточно сравнить id. @answer.user_id не делает лишнего запроса к базе, т.к. это атрибут самого ответа и он уже загружен в память

2016-10-18 13:46 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to @answer.question, notice: 'Ваш ответ удалён'
У тебя редирект в обоих случаях один и тот же, только сообщение меняется. Значит, надо его из условия вынести, оставив только установку сообщений, иначе дублирование получается

2016-10-18 13:46 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if @question.user == current_user
Опять же, нужно сравнивать по id. И т.к. такая проверка встретится еще не раз, то вынеси ее в метод модели User, чтобы вызывать так: `current_user.author_of?(@question)`.  И не забудь тесты модели написать на этот метод

2016-10-18 13:46 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +      redirect_to question_path(@question), notice: 'Удалить можно только свой вопрос'
Можно короче: `redirect_to @question, notice: '...'`

2016-10-18 13:46 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +  - if user_signed_in? && answer.user == current_user
Замени проверку на авторство на метод `User#author_of?`

2016-10-18 13:46 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  if @question.user == current_user
Замени на вызов `User#author_of?`

2016-10-18 13:46 UTC, vkurennov commented on app/views/questions/show.html.slim
> +    = link_to 'Удалить вопрос', question_path(@question), method: 'delete', data: { confirm: 'Вы уверены?' }
Вторым параметром можно просто @question передавать

2016-10-18 13:46 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { post :create, params: { answer: attributes_for(:answer, user_id: question.user), question_id: question } }.to change(question.answers, :count).by(1)
user_id не передается в параметрах, мы же его берем сразу в контроллере как current_user, иначе можно было бы любое значение подставить и создать ответ от любого юзера.

2016-10-18 13:46 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>        it 'saves new answer' do
Нужен еще тест на то, что созданный ответ связывается в залогиненным юзером

2016-10-18 13:46 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>      end
user_id не передается в параметрах

2016-10-18 13:46 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { post :create, params: { answer: attributes_for(:invalid_answer), question_id: question } }.to_not change(question.answers, :count)
Тут в change должен быть просто Answer, т.к. важно проверить, что в принципе не создан ответ, вне зависимости от его связей.

2016-10-18 13:46 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +  describe 'DELETE #destroy' do
Тут должно быть 2 контекста: для автора и для не-автора

2016-10-18 13:46 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      expect { delete :destroy, params: { id: answer } }.to_not change(@user.answers, :count)
описание теста и его реализация явно противоречат друг другу

2016-10-18 13:46 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        expect { post :create, params: { question: attributes_for(:invalid_question) } }.to_not change(@user.questions, :count)
тут просто Question в change должен быть

2016-10-18 13:46 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +  describe 'DELETE #destroy' do
2 контекста: автор успешно удаляет вопрос, и не-автор не может удалить чужой вопрос

2016-10-18 13:46 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +      expect { delete :destroy, params: { id: question } }.to_not change(@user.questions, :count)
и опять реализация и описание не совпадают. И почему, кстати, это проходит? Ведь у нас залогинен @user, он же удаляет ответ. Точнее я понимаю, почему: мы создаем и тут же удаляем ответ, но тест получается ничего не тестирует, т.к. он пройдет и в том случае, если вызова destroy вообще не будет в контроллере.

Нужно объект создать ДО теста. Для этого надо объявить его через метод `let!`, этот метод вызывается перед каждым тестом

2016-10-18 13:46 UTC, vkurennov commented on spec/features/create_answer_spec.rb
> +feature 'Create answer', %q{
Еще нужен сценарий на невалидную форму. Сами валидации проверять не надо, это мы делаем в модели, но нужно проверить, что система сообщила пользователю об ошибке

2016-10-18 13:46 UTC, vkurennov commented on spec/features/create_answer_spec.rb
> +    visit new_question_answer_path(question)
Форма ответа должна быть на странице вопроса, это указано в задании (сейчас добавил пояснение этого пункта в задание)

2016-10-18 13:46 UTC, vkurennov commented on spec/features/create_question_spec.rb
> +    expect(page).to have_content('Test question content')
Надо еще и заголовок ответа проверить

2016-10-18 13:46 UTC, vkurennov commented on spec/features/create_question_spec.rb
> +feature 'Create question', %q{
Также нужен сценарий на попытку создать невалидный вопрос

2016-10-18 13:46 UTC, vkurennov commented on spec/features/delete_answer_spec.rb
> +    page.driver.submit :delete, answer_path(answer), {}
Никаких submit'ов, только клики по ссылкам. Acceptence-тесты пишутся как для живого тестера (по возможности, конечно). Ты же не будешь писать живому тестеру "пошли запрос на удаление", ты напишешь "нажми ссылку Удалить ответ"

2016-10-18 13:46 UTC, vkurennov commented on spec/features/delete_answer_spec.rb
> +    expect(page).to have_content 'Ваш ответ удалён'
Надо проверить, что ответа больше нет на странице

2016-10-18 13:46 UTC, vkurennov commented on spec/features/delete_answer_spec.rb
> +    page.driver.submit :delete, answer_path(answer2), {}
клик по ссылке

2016-10-18 13:46 UTC, vkurennov commented on spec/features/delete_answer_spec.rb
> +    expect(page).to have_content 'Удалить можно только свой ответ'
И надо проверить, что ответ по-прежнему есть на странице

2016-10-18 13:46 UTC, vkurennov commented on spec/features/delete_answer_spec.rb
> +    page.driver.submit :delete, answer_path(answer), {}
Нужно просто проверить, что нет ссылки на удаление

2016-10-18 13:46 UTC, vkurennov commented on spec/features/delete_answer_spec.rb
> +    page.driver.submit :delete, answer_path(answer2), {}
А точнее - надо провеить, что ссылки на странице нет. А отправку запроса в обход интерфейса мы должны проверять в тестах контроллера

2016-10-18 13:46 UTC, vkurennov commented on spec/features/delete_question_spec.rb
> +    page.driver.submit :delete, question_path(question), {}
Клик по ссылке

2016-10-18 13:46 UTC, vkurennov commented on spec/features/delete_question_spec.rb
> +    expect(page).to have_content 'Ваш вопрос удалён'
Проверить, что вопроса  больше нет в списке

2016-10-18 13:46 UTC, vkurennov commented on spec/features/delete_question_spec.rb
> +    page.driver.submit :delete, question_path(question2), {}
Проверить, что ссылки на удаление нет на странцие

2016-10-18 13:46 UTC, vkurennov commented on spec/features/delete_question_spec.rb
> +    page.driver.submit :delete, question_path(question), {}
Проверить, что ссылки на удаление нет на странцие

2016-10-18 13:46 UTC, vkurennov commented on spec/features/index_questions_spec.rb
> +    expect(page).to have_selector('.js-question', count: 5)
Не надо привязываться к верстке, насколько это возможно. Нужно через  sequence в фабриках сделать разные вопросы и проверить, что они все есть на странице

2016-10-18 13:46 UTC, vkurennov commented on spec/features/index_questions_spec.rb
> +    expect(page).to have_selector('a.js-give-answer', count: 5)
Тут то же самое для ответов

2016-10-18 13:46 UTC, vkurennov commented on spec/features/index_questions_spec.rb
> +    expect(page).to have_selector('a.js-give-answer', count: 0)
Во-первых, тут те же замечания, что и к предыдущему сценарию, во-вторых, какой смысл проверять кол-во ответов на странице **со списком вопросов**?

2016-10-18 13:46 UTC, vkurennov commented on spec/features/show_question_spec.rb
> +    expect(page).to have_selector('.js-give-answer', count: 1)
Проверяй контент, а не структуру страницы

2016-10-18 13:46 UTC, vkurennov commented on spec/features/show_question_spec.rb
> +    expect(page).to have_selector('.js-give-answer', count: 0)
И что это проверяет? Что ответов нет? Ок, но описание теста говорит о другом.

2016-10-18 19:07 UTC, selivanov-d commented on app/controllers/answers_controller.rb
>        render :new
Перенёс.

2016-10-18 19:14 UTC, selivanov-d commented on app/controllers/answers_controller.rb
> +    if @answer.user == current_user
Спасибо за подсказку! Проверил, действительно так. :)
Поправил.

2016-10-18 19:17 UTC, selivanov-d commented on app/controllers/answers_controller.rb
> +      redirect_to @answer.question, notice: 'Ваш ответ удалён'
Поправил.

2016-10-18 19:29 UTC, selivanov-d commented on app/views/questions/show.html.slim
> +    = link_to 'Удалить вопрос', question_path(@question), method: 'delete', data: { confirm: 'Вы уверены?' }
Здесь и в других подобных местах убрал лишний вызов хэлпера.

2016-10-18 19:44 UTC, selivanov-d commented on spec/controllers/answers_controller_spec.rb
> +        expect { post :create, params: { answer: attributes_for(:invalid_answer), question_id: question } }.to_not change(question.answers, :count)
Действительно. В который раз забываю о том, что при неуспешном создании разумно делать более широкую проверку. 
Поправил.

2016-10-18 19:44 UTC, selivanov-d commented on spec/controllers/questions_controller_spec.rb
> +        expect { post :create, params: { question: attributes_for(:invalid_question) } }.to_not change(@user.questions, :count)
Поправил.

2016-10-18 19:45 UTC, selivanov-d commented on spec/features/create_answer_spec.rb
> +    visit new_question_answer_path(question)
Поправил.

2016-10-18 19:46 UTC, selivanov-d commented on spec/features/create_question_spec.rb
> +    expect(page).to have_content('Test question content')
У ответа нет заголовка. Или я что-то не так понял?

2016-10-18 20:29 UTC, selivanov-d commented on spec/features/delete_answer_spec.rb
> +    page.driver.submit :delete, answer_path(answer), {}
Ага, понятно. 
Здесь и в других подобных местах поправил.

2016-10-18 20:30 UTC, selivanov-d commented on spec/features/delete_answer_spec.rb
> +    page.driver.submit :delete, answer_path(answer), {}
Поправил.

2016-10-18 20:30 UTC, selivanov-d commented on spec/features/delete_question_spec.rb
> +    page.driver.submit :delete, question_path(question), {}
Поправил.

2016-10-18 20:31 UTC, selivanov-d commented on spec/features/delete_question_spec.rb
> +    page.driver.submit :delete, question_path(question2), {}
Поправил.

2016-10-18 20:31 UTC, selivanov-d commented on spec/features/delete_question_spec.rb
> +    page.driver.submit :delete, question_path(question), {}
Поправил.

2016-10-18 20:31 UTC, selivanov-d commented on spec/features/delete_answer_spec.rb
> +    page.driver.submit :delete, answer_path(answer2), {}
Поправил.

2016-10-19 09:29 UTC, selivanov-d commented on spec/features/create_question_spec.rb
> +feature 'Create question', %q{
Добавил.

2016-10-19 09:29 UTC, selivanov-d commented on spec/features/create_answer_spec.rb
> +feature 'Create answer', %q{
Добавил.

2016-10-19 09:56 UTC, selivanov-d commented on spec/controllers/answers_controller_spec.rb
> +      expect { delete :destroy, params: { id: answer } }.to_not change(@user.answers, :count)
Противоречат в том смысле, что конструкция `to_not change()` намекает на то, что ничего не изменилось? Ну да, есть такое.
Решил через создание ответа через `let!`.

2016-10-19 10:15 UTC, selivanov-d commented on spec/controllers/answers_controller_spec.rb
> +  describe 'DELETE #destroy' do
Добавил.

2016-10-19 11:02 UTC, selivanov-d commented on spec/controllers/answers_controller_spec.rb
> +        expect { post :create, params: { answer: attributes_for(:answer, user_id: question.user), question_id: question } }.to change(question.answers, :count).by(1)
Поправил. Помню, что почему-то у меня без этого не проходили тесты.

2016-10-19 11:02 UTC, selivanov-d commented on spec/controllers/answers_controller_spec.rb
>      end
Убрал.

2016-10-19 11:07 UTC, selivanov-d commented on spec/controllers/answers_controller_spec.rb
>        it 'saves new answer' do
Добавил.

2016-10-19 11:08 UTC, selivanov-d commented on app/controllers/questions_controller.rb
> +      redirect_to question_path(@question), notice: 'Удалить можно только свой вопрос'
Поправил.

2016-10-19 11:15 UTC, selivanov-d commented on spec/controllers/questions_controller_spec.rb
> +  describe 'DELETE #destroy' do
Добавил.

2016-10-19 11:17 UTC, selivanov-d commented on spec/controllers/questions_controller_spec.rb
> +      expect { delete :destroy, params: { id: question } }.to_not change(@user.questions, :count)
Да, методом `let!` и решил проблему. Оказалось, что `let`, в отличие от `let!` выполняется не сразу.

2016-10-19 11:20 UTC, selivanov-d commented on spec/features/delete_answer_spec.rb
> +    expect(page).to have_content 'Ваш ответ удалён'
Добавил.

2016-10-19 11:23 UTC, selivanov-d commented on spec/features/delete_answer_spec.rb
> +    expect(page).to have_content 'Удалить можно только свой ответ'
После изменения кода попытка удаления чужого ответа больше невозможна.

2016-10-19 11:28 UTC, selivanov-d commented on spec/features/delete_question_spec.rb
> +    expect(page).to have_content 'Ваш вопрос удалён'
Добавил.

2016-10-19 12:01 UTC, selivanov-d commented on spec/features/index_questions_spec.rb
> +    expect(page).to have_selector('.js-question', count: 5)
Поправил.

2016-10-19 12:02 UTC, selivanov-d commented on spec/features/index_questions_spec.rb
> +    expect(page).to have_selector('a.js-give-answer', count: 5)
Заменил на проверку наличия ссылки по названию.

2016-10-19 12:03 UTC, selivanov-d commented on spec/features/index_questions_spec.rb
> +    expect(page).to have_selector('a.js-give-answer', count: 0)
Это не количество ответов, это количество ссылок на страницу дачи ответа. :)
Заменил на проверку отсутствия таких ссылок по названию.

2016-10-19 12:14 UTC, selivanov-d commented on spec/features/show_question_spec.rb
> +    expect(page).to have_selector('.js-give-answer', count: 1)
Поправил.

2016-10-19 12:15 UTC, selivanov-d commented on spec/features/show_question_spec.rb
> +    expect(page).to have_selector('.js-give-answer', count: 0)
Это ищется кнопка на страницу с формой ответа. Исправил этот момент.

2016-10-19 12:45 UTC, selivanov-d commented on app/views/answers/_answer.html.slim
> +  - if user_signed_in? && answer.user == current_user
Сделал.

2016-10-19 12:45 UTC, selivanov-d commented on app/views/questions/show.html.slim
> +  if @question.user == current_user
Сделал.

2016-10-19 12:45 UTC, selivanov-d commented on app/controllers/questions_controller.rb
> +    if @question.user == current_user
Сделал.

2016-10-20 11:38 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      expect { delete :destroy, params: { id: answer } }.to_not change(@user.answers, :count)
Верно решил, и да, именно это я и имел в виду (про to_not)

2016-10-20 11:39 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +      expect { delete :destroy, params: { id: question } }.to_not change(@user.questions, :count)
Все верно, let - "ленивый метод", выполняется в момент первого вызова

2016-10-20 11:41 UTC, vkurennov commented on spec/features/create_question_spec.rb
> +    expect(page).to have_content('Test question content')
Тест-то для вопроса, это я опечатался :-)

2016-10-20 11:42 UTC, vkurennov commented on spec/features/show_question_spec.rb
> +    expect(page).to have_selector('.js-give-answer', count: 0)
Форма должна быть на странцие вопроса, ну и как видишь, привязка к классам ухудшает понимание кода теми, кто его читает

2016-10-20 11:50 UTC, vkurennov approved these changes
Отлично, принято. Обрати внимание на комментарии

2016-10-20 11:50 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  - if current_user.author_of?(@question)
Объедени в один if с составным условием, зачем пложить вложенные if'ы?

2016-10-20 11:50 UTC, vkurennov commented on spec/features/create_question_spec.rb
> +      expect(page).to have_content('[:title] is too long (maximum is 255 characters)')
Достаточно было только на пустое поле проверить. Как я уже писал, не надо на все валидации писать тест, это есть в моделях, важно проверить, что сообщения в принципе выводятся

2016-10-20 11:50 UTC, vkurennov commented on spec/models/user_spec.rb
> +      expect(user.author_of?(question)).to eq true
Для методов-предикатов (на знак вопроса заканчиваются), если фишка в rsepc, можно их использовать как матчеры (в правой части): `expect(user).to be_author_of(question)`.

Т.е. добавляешь be_ и убираешь знак вопроса

2016-10-20 13:50 UTC, selivanov-d commented on spec/models/user_spec.rb
> +      expect(user.author_of?(question)).to eq true
Точно! Это ж было в скринкасте. :)

2016-10-20 13:51 UTC, selivanov-d commented on app/views/questions/show.html.slim
> +  - if current_user.author_of?(@question)
Тут, мне кажется, нужен вложенный `if`. Оставлю.

2016-10-20 13:51 UTC, merged