Lesson 7
selivanov-d/questions_answered pull request #5
Opened 2016-10-26 12:37 UTC by selivanov-d

Added Lesson 7

2016-10-26 20:30 UTC, vkurennov requested changes
Исправь замечания

2016-10-26 20:30 UTC, vkurennov commented on app/assets/javascripts/scripts.js
> +            case 'error':
Тогда уж и надо обрабатывать ajax:error, правда, об этом мы в 9-м уроке поговорим.

2016-10-26 20:30 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +        render json: { status: 'success', data: 'Ваш ответ успешно изменён'.force_encoding('UTF-8') }, status: :ok
Пока надо было делать через js-ответы, на json перейдем в 9-м уроке. Но уже оставь, что теперь :-)

2016-10-26 20:30 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      render json: { message: 'Отметить ответ лучшим можно у своего вопроса'.force_encoding('UTF-8') }, status: :forbidden
Чтобы не форсить кодировку, добавь в начале файла комментарий:

`#encoding: utf-8`

Ну и сам файл в utf-8 сохрани

2016-10-26 20:30 UTC, vkurennov commented on app/models/answer.rb
> +    current_best = Answer.best_for(question_id).first
Тут надо все в [транзакцию](http://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html) обернуть, чтобы изменения атомарныем были

2016-10-26 20:30 UTC, vkurennov commented on app/models/answer.rb
> +    self.best = true
Лучше сохранять прямо здесь. Опять же, чтобы изменения были атомарными.

2016-10-26 20:30 UTC, vkurennov commented on config/routes.rb
> +        post 'mark_as_best' => 'answers#mark_as_best'
У тебя и так это внутри ресурса answers, в этом случае не указывается куда ведет роут, если значения по-умолчанию совпадают.

2016-10-26 20:30 UTC, vkurennov commented on spec/models/answer_spec.rb
> +      #   answer.mark_as_best
Во-первых, не используй тестируемый метод для установки значений, ведь если там баг, то мы не можем быть уверены, что тест верный. Т.е. напрямую сначала одному из ответов задай флаг в true.

Во-вторых, это может быть из-за того, что атрибут в методе не сохраняется, а только устанавливается.

2016-10-27 08:07 UTC, selivanov-d commented on app/controllers/answers_controller.rb
> +      render json: { message: 'Отметить ответ лучшим можно у своего вопроса'.force_encoding('UTF-8') }, status: :forbidden
Удивительно, но убрав `.force_encoding('UTF-8')` все тесты проходят. Не понимаю почему в самом начале написания с ними были проблемы.

2016-10-27 08:50 UTC, selivanov-d commented on app/models/answer.rb
> +    current_best = Answer.best_for(question_id).first
Спасибо за напоминание, забыл о транзакциях. :)

2016-10-27 08:51 UTC, selivanov-d commented on app/models/answer.rb
> +    self.best = true
Поправил.

2016-10-27 08:52 UTC, selivanov-d commented on spec/models/answer_spec.rb
> +      #   answer.mark_as_best
Всё оказалось проще -- надо было просто перезагружать модель `best_answer` из БД после вызова метода `Answer.mark_as_best`.

2016-10-27 09:03 UTC, selivanov-d commented on config/routes.rb
> +        post 'mark_as_best' => 'answers#mark_as_best'
Убрал лишнее.

2016-10-27 09:17 UTC, selivanov-d commented on app/assets/javascripts/scripts.js
> +            case 'error':
Если я правильно понял, `ajax:error` вызывается на ответы с кодами ошибок 4xx, а у меня ошибочный ответ идёт с кодом 200, но в JSON есть поле `status: error` если, например, есть ошибка валидации переданных пользователем данных. Такое поведение предсказуемо, его я  обрабатываемо. Возможно на такой случай можно было бы отвечать каким-то другим кодом, но я не нашёл каким: семейство 4хх для этого не подходит.
Есть ещё ошибки, которые отвечают кодом 403, но это только в хитрых случаях типа вызова метода контроллера для незалогиненного пользователя и из интерфейса этого сделать нельзя.

2016-10-27 14:30 UTC, vkurennov approved these changes
Принято, но поправь замечания

2016-10-27 14:30 UTC, vkurennov commented on app/assets/javascripts/scripts.js
> +            case 'error':
Просто если уж ты отвечаешь статусами, то и надо их использовать правильно, и если, скажем ошибка валидации, то самое правильное вернуть статус 422 unprocessible entity. Но это в любом случае оставь до 9-го занятия

2016-10-27 14:30 UTC, vkurennov commented on app/models/answer.rb
> +      current_best.update_attributes(best: false) if current_best.present?
Транзакция откатывается только в случае исключений, чтобы апдей выкидвал исклюкчение, то надо использовать bang-версию, т.е. update! и строкой ниже тоже.

2016-10-27 14:44 UTC, selivanov-d commented on app/models/answer.rb
> +      current_best.update_attributes(best: false) if current_best.present?
Поправил.

2016-10-27 14:44 UTC, merged