Lesson 8
selivanov-d/questions_answered pull request #6
Opened 2016-11-01 15:41 UTC by selivanov-d

Added Lesson 8

2016-11-01 17:01 UTC, vkurennov requested changes
А где же acceptance-тесты на добавление/удаление файлов?

2016-11-01 17:01 UTC, vkurennov commented on app/controllers/attachments_controller.rb
> +    parent_class = @attachment.attachable_type.constantize
Все гораздо проще. У нас же уже есть полиморфная ассоциация у аттачмента, значит, чтобы получить родителський объект, достаточно обратиться к ней: `@attchment.attachable`

2016-11-01 17:01 UTC, vkurennov commented on app/models/answer.rb
> +  accepts_nested_attributes_for :attachments
Тут нужна опция rejected_if, чтобы не было ошибки валидации, когда сначала добавляешь файл, а потом, еще до создания объекта, отменяешь добавление.

2016-11-01 17:01 UTC, vkurennov commented on app/models/question.rb
> +  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true
Вот эти же опции должны быть и в Answer

2016-11-01 17:01 UTC, vkurennov commented on config/initializers/assets.rb
> +Rails.application.config.assets.precompile += %w( cocoon.js )
Если включить файл в application.js, как того требует документация, то здесь ничего не надо будет добавлять

2016-11-01 18:44 UTC, selivanov-d commented on app/controllers/attachments_controller.rb
> +    parent_class = @attachment.attachable_type.constantize
Действительно. Забыл об этом, наверное, потому, что по имени "attachable" не сразу можно понять, что речь идёт о "родительском" ресурсе. 
Поправил.

2016-11-01 19:09 UTC, selivanov-d commented on app/models/answer.rb
> +  accepts_nested_attributes_for :attachments
Добавил. Заодно прочитал [документацию](http://api.rubyonrails.org/classes/ActiveRecord/NestedAttributes/ClassMethods.html) по методу `accepts_nested_attributes_for `. Стало понятнее что такое `reject_if`.

2016-11-01 19:09 UTC, selivanov-d commented on app/models/question.rb
> +  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true
Добавил.

2016-11-01 19:16 UTC, selivanov-d commented on config/initializers/assets.rb
> +Rails.application.config.assets.precompile += %w( cocoon.js )
Когда подключал гем, видимо, не перезагрузил сервер после добавления строки в application.js. Из-за чего приложение падало с ошибкой, которую я решил путём добавления строки в assets.rb.
Поправил.

2016-11-02 09:08 UTC, vkurennov requested changes
Надо поправить тесты и добавь папку public/uploads в .gitignore, чтобы не засорять репозиторий файлами с dev-окружения

2016-11-02 09:08 UTC, vkurennov commented on spec/features/create_answer_spec.rb
> +        file_input[0].set(Rails.root + 'spec/support/files/test-file.jpg')
Надо проверить добавление нескольких файлов

2016-11-02 09:08 UTC, vkurennov commented on spec/features/create_question_spec.rb
> +        file_input[0].set(Rails.root + 'spec/support/files/test-file.jpg')
Надо проверить добавление нескольких файлов

2016-11-07 11:25 UTC, merged