Lesson 9
selivanov-d/questions_answered pull request #7
Opened 2016-11-13 17:49 UTC by selivanov-d

Added Lesson 9

2016-11-14 10:03 UTC, vkurennov requested changes
Исправь замечания

2016-11-14 10:03 UTC, vkurennov commented on app/assets/javascripts/scripts.js
> +        case 'success':
А зачем case,  если тут всего 1 вариант? Почему не if?

2016-11-14 10:03 UTC, vkurennov commented on app/assets/javascripts/scripts.js
> +        case 'success':
И тут тот же вопрос

2016-11-14 10:03 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +    before_action :check_votable_ownership, only: [:upvote, :downvote]
Тут есть проблема. Штука в том, что фильтры в контроллере выполняются в порядке их указания, а т.к. модуль включается в контролер ДО вызова   `before_action :authenticate_user!`, то на момент отработки check_votable_ownership у тебя еще нет залогиненного юзера, т.е. current_user возвращает nil.

Самое верное - переставить вызов модуля Voted после вызова всех before_action из контроллера.

2016-11-14 10:03 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +    if @votable.user == current_user
Во-первых, сравнивать  надо по id, уже не раз это проходили, во-вторых, у тебя есть метод `User#author_of?` для этого.

2016-11-14 10:03 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  include Voted
Тут тоже лучше перенести подключение модуля после блока фильтров

2016-11-14 10:03 UTC, vkurennov commented on app/models/concerns/votable.rb
> +    has_many :attachments, as: :attachable, dependent: :destroy
Идея консернов в логической связанности. Какое отношение имеют аттачменты к голосованию? Их нужно вынести в отдельный консерн

2016-11-14 10:03 UTC, vkurennov commented on app/models/concerns/votable.rb
> +    belongs_to :user
Это тоже не имеет отношения к голосованию (прямого)

2016-11-14 10:03 UTC, vkurennov commented on app/models/concerns/votable.rb
> +    accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true
И это тоже лишнее, и имеет отношение к аттачментам

2016-11-14 10:03 UTC, vkurennov commented on app/models/concerns/votable.rb
> +    user.votes.create(votable: self, value: 1)
Тогда уж лучше юзера указывать: `votes.create(user: user,  value: 1)`, а то как-то странно получается.

2016-11-14 10:03 UTC, vkurennov commented on app/models/concerns/votable.rb
> +    user.votes.create(votable: self, value: -1)
Мы же в контексте объекта и его методов работаем, вот и надо обращаться к его ассоциациям, а доп. условием передавать юзера.

2016-11-14 10:03 UTC, vkurennov commented on app/models/concerns/votable.rb
> +    user.votes.by_votable(self).destroy_all
И тут надо искать через ассоциации объекта, предавая юзера

2016-11-14 10:03 UTC, vkurennov commented on app/models/concerns/votable.rb
> +    Vote.where(votable: self).sum(:value)
А чем обращение к ассоциации votes текущего объекта не устраивает?

2016-11-14 10:03 UTC, vkurennov commented on app/models/concerns/votable.rb
> +  def has_vote_from?(user)
А вот этот метод я бы вообще в User перенес

2016-11-14 10:03 UTC, vkurennov commented on app/models/concerns/votable.rb
> +    Vote.by_user(user).by_votable(self).any?
`votes.where(user: user).exists?`. Так мы не грузим объекты в память, а просто делаем запрос к базе на существование нужной записи

2016-11-14 10:03 UTC, vkurennov commented on app/models/vote.rb
> +  belongs_to :votable, optional: true, polymorphic: true
То есть, голос может существовать без объекта, за который он создан?

2016-11-14 10:03 UTC, vkurennov commented on app/models/vote.rb
> +  scope :by_user, ->(user) { where(user: user) }
Не вижу смысла в этих скоупах, все решается путем обращения к ассоциациям родительского объекта

2016-11-14 10:03 UTC, vkurennov commented on app/views/questions/_question-content.html.slim
> +      = link_to upvote_question_path, method: 'post', remote: true,
Очень похожие блоки для голосования за вопрос ответ. Надо вынести в паршл и параметризировать через передачу аргументов

2016-11-14 10:03 UTC, vkurennov commented on spec/features/vote_for_answer_spec.rb
> +          expect(page).to_not have_content('+1')
Это уже проверено в предыдущем тесте, нет смысла заново проверять

2016-11-14 10:03 UTC, vkurennov commented on spec/features/vote_for_answer_spec.rb
> +      scenario 'tries to downvote an answer twice', js: true do
Опять лишний тест, это уже проверено.

2016-11-14 19:02 UTC, selivanov-d commented on app/controllers/concerns/voted.rb
> +    before_action :check_votable_ownership, only: [:upvote, :downvote]
Действительно, не подумал об этом. Поправил.
Но, проверив "current_user возвращает nil", с удивлением обнаружил, что этот метод таки возвращает залогиненного юзера. Порядок же коллбэков правильный -- в порядке объявления и методы из консёрна в том месте, где он включается в контроллер. 
Есть идеи почему так?

2016-11-14 19:10 UTC, selivanov-d commented on app/controllers/concerns/voted.rb
> +    if @votable.user == current_user
Тот неловкий момент, когда преподаватель знает твой код лучше тебя. :)
Поправил.

2016-11-14 19:10 UTC, selivanov-d commented on app/controllers/questions_controller.rb
> +  include Voted
Поправил.

2016-11-14 19:43 UTC, selivanov-d commented on app/models/concerns/votable.rb
> +    has_many :attachments, as: :attachable, dependent: :destroy
Да, забыл об этом. Вернул объявления связей в модели. С созданием под attachments отдельного concern'а решил не связываться, т.к. опасаюсь застрять ещё на пару дней с изменением кода и написанием под это дело тестов.

2016-11-14 19:43 UTC, selivanov-d commented on app/models/concerns/votable.rb
> +    belongs_to :user
Вынес.

2016-11-14 19:43 UTC, selivanov-d commented on app/models/concerns/votable.rb
> +    accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true
Вынес.

2016-11-14 19:48 UTC, selivanov-d commented on app/models/concerns/votable.rb
> +    user.votes.create(votable: self, value: 1)
Поправил.

2016-11-14 19:48 UTC, selivanov-d commented on app/models/concerns/votable.rb
> +    user.votes.create(votable: self, value: -1)
Поправил.

2016-11-14 19:54 UTC, selivanov-d commented on app/models/concerns/votable.rb
> +    Vote.where(votable: self).sum(:value)
У меня нет ответа. :)
Поправил.

2016-11-14 19:58 UTC, selivanov-d commented on app/models/concerns/votable.rb
> +    user.votes.by_votable(self).destroy_all
Поправил.

2016-11-15 17:58 UTC, selivanov-d commented on spec/features/vote_for_answer_spec.rb
> +          expect(page).to_not have_content('+1')
Да, действительно. Убрал.

2016-11-15 17:58 UTC, selivanov-d commented on spec/features/vote_for_answer_spec.rb
> +      scenario 'tries to downvote an answer twice', js: true do
Убрал.

2016-11-15 18:15 UTC, selivanov-d commented on app/models/vote.rb
> +  belongs_to :votable, optional: true, polymorphic: true
Похоже, откуда-то скопировал строку и не убрал параметр.
Исправил.

2016-11-15 18:27 UTC, selivanov-d commented on app/models/vote.rb
> +  scope :by_user, ->(user) { where(user: user) }
А как тогда переписать выбор всех голосов у `votable` по пользователю
`votable.votes.by_user(user)`
Как-то так?
`votable.votes.where(user: user)`

Если так, то принципиальной разницы между вариантами я не вижу и, пожалуй, оставлю свой вариант.

2016-11-15 18:41 UTC, selivanov-d commented on app/models/concerns/votable.rb
> +    Vote.by_user(user).by_votable(self).any?
Спасибо, постараюсь запомнить. 
Поправил.

2016-11-15 18:46 UTC, selivanov-d commented on app/assets/javascripts/scripts.js
> +        case 'success':
Поправил.

2016-11-15 18:52 UTC, selivanov-d commented on app/assets/javascripts/scripts.js
> +        case 'success':
На самом деле это был задел на то, чтобы обрабатывать потенциальные ошибки, которые могут вернуться от сервера если добавить/удалить голос не удастся. Но такая ситуация маловероятна, учитывая, что кнопки "+1/-1" скрыты после первого голосования (что проверяется тестами), а других поводов для ошибки быть не может. Т.е. может, конечно, случиться ошибка сервера или что-то типа того, но такие случаи, думаю, за пределами курса. 
Так что `switch` тут действительно лишний, убрал его. Лишний, может быть, и `if`, но пусть останется на всякий случай. :)

2016-11-15 19:18 UTC, selivanov-d commented on app/views/questions/_question-content.html.slim
> +      = link_to upvote_question_path, method: 'post', remote: true,
Сделал.

2016-11-16 12:07 UTC, vkurennov requested changes
Допиши тесты на скоупы

2016-11-16 12:07 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +    before_action :check_votable_ownership, only: [:upvote, :downvote]
Смотря где проверял, если в экшене, то там ведь уже все фильтры выполнены, неверный current_user может быть только внутри check_votable_ownership.

2016-11-16 12:07 UTC, vkurennov commented on app/models/vote.rb
> +  scope :by_user, ->(user) { where(user: user) }
Да. именно так `votable.votes.where(user: user)`, разница в том, что ты на стандартный вариант, который работает из коробки пишешь свой вариант. Зачем? А если представить, что мы работаем в команде. Один будет писать так, другой эдак и будут тебе задавать логичный вопрос: а зачем этот скуоп, если есть where? Но оставь, я не против, просто не увлекайся такими вещами, есть более важные задачи на которые стоит время тратить, а все стандартное пусть делает фреймворк

2016-11-16 12:07 UTC, vkurennov commented on app/models/vote.rb
> +  scope :by_votable, ->(votable) { where(votable: votable) }
Ну и раз уж решил оставить кастомные скоупы, то где на них тесты?

2016-11-16 18:49 UTC, selivanov-d commented on app/models/vote.rb
> +  scope :by_votable, ->(votable) { where(votable: votable) }
Таки отказался от скоупов в пользу метода `where`. Во-первых, осознал их бесполезность, во-вторых, их тестирование мы не проходили, а в интернете я нашёл по этой теме мало информации да и та датирована 2009-2011 годом.

Затрудняюсь сказать почему не использовал такой подход сразу. Необъяснимо, но использование `where` мне казалось каким-то хаком, типа написания SQL-запроса там, где есть класс для работы с БД. Постараюсь отучить себя от этой привычки.

2016-11-17 08:02 UTC, vkurennov approved these changes

2016-11-17 12:01 UTC, merged